// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFfy2w-kQM11TOLQ6-BLP5HA2oiriJqA',
    appId: '1:135794159266:web:79cb72bcb41bf0dd84b1fb',
    messagingSenderId: '135794159266',
    projectId: 'todoapp-acb99',
    authDomain: 'todoapp-acb99.firebaseapp.com',
    storageBucket: 'todoapp-acb99.firebasestorage.app',
    measurementId: 'G-H45S07CK4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtz2aFj6IH9gSrbdJ2yD_pyJb88fGwT8',
    appId: '1:135794159266:android:cf82d772c3d0182384b1fb',
    messagingSenderId: '135794159266',
    projectId: 'todoapp-acb99',
    storageBucket: 'todoapp-acb99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjF-A0kv1Rex1fcv5Luk_GtgwaQmIOvV0',
    appId: '1:135794159266:ios:b227dbf342367df184b1fb',
    messagingSenderId: '135794159266',
    projectId: 'todoapp-acb99',
    storageBucket: 'todoapp-acb99.firebasestorage.app',
    iosBundleId: 'com.example.todoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjF-A0kv1Rex1fcv5Luk_GtgwaQmIOvV0',
    appId: '1:135794159266:ios:b227dbf342367df184b1fb',
    messagingSenderId: '135794159266',
    projectId: 'todoapp-acb99',
    storageBucket: 'todoapp-acb99.firebasestorage.app',
    iosBundleId: 'com.example.todoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOFfy2w-kQM11TOLQ6-BLP5HA2oiriJqA',
    appId: '1:135794159266:web:241c946418c409ad84b1fb',
    messagingSenderId: '135794159266',
    projectId: 'todoapp-acb99',
    authDomain: 'todoapp-acb99.firebaseapp.com',
    storageBucket: 'todoapp-acb99.firebasestorage.app',
    measurementId: 'G-HZWRC37T0N',
  );
}
